Music_Therapy_API/urls.py
# Copyright 2024 Yuan Chen
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Music_Therapy_API URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.db import router
from django.urls import include, path

# import patient_management

urlpatterns = [
    path("", include("app.urls")),
    path("email/", include("email_service.urls")),
    path("admin/", admin.site.urls),
    path("patient/", include("patient_management.urls")),
    path("music/", include("music_management.urls")),
    path("chat/", include("chat.urls")),
    path("accounts/", include("accounts.urls")),
    path("assessment/", include("assessment.urls")),
    path("sheetRAS/", include("sheetRAS.urls")),
    path("sheet4AT/", include("sheet4AT.urls")),
    # path('sheetCAM/', include('sheetCAM.urls')),
    path("sheetCAM1/", include("sheetCAM1.urls")),
    path("findatherapist/", include("findatherapist.urls")),
    path("sheetAAQII/", include("sheetAAQII.urls")),
    path("sheetGAD/", include("sheetGAD.urls")),
    path("sheetPHQ/", include("sheetPHQ.urls")),
    path("api/", include("api.urls")),
]

api/urls.py
from django.urls import include, path
from rest_framework import routers

from api import views

router = routers.DefaultRouter()
router.register(r"users", views.UserViewSet)
router.register(r"groups", views.GroupViewSet)
router.register(r"songs", views.SongViewSet)
router.register(r"playlists", views.PlaylistViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path("", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

urlpatterns += router.urls

assessment/urls.py
from django.contrib import admin
from django.db import router
from django.urls import include, path, re_path

from assessment.views import (AAQ2View, AT4View, CAM1View, GAD7View,
                              NeurologicScreeningEvaluationView, PHQ9View,
                              PrePostView,
                              PsychoemotionalScreeningEvaluationView, RASView,
                              StompSuccessView, StompView)

from . import views

# import patient_management
app_name = "assessment"

urlpatterns = [
    # path('stomp/', views.stomp, name='stomp'),
    re_path(r"^$", views.index),
    re_path(r"^download/$", views.render_pdf),
    path("", views.index, name="index"),
    path("stomp/", StompView.as_view(), name="stomp"),
    path("success/", StompSuccessView.as_view(), name="success"),
    path(
        "neurologic_screening_evaluation/",
        NeurologicScreeningEvaluationView.as_view(),
        name="Neurologic_Screening_Evaluation",
    ),
    path("pre_post_tests/", PrePostView.as_view(), name="pre_post_tests"),
    path(
        "Psychoemotional_Screening_Evaluation/",
        PsychoemotionalScreeningEvaluationView.as_view(),
        name="Psychoemotional_Screening_Evaluation",
    ),
    path("pdf/", views.some_view, name="pdf"),
    path("AT4/", AT4View.as_view(), name="AT4"),
    path("AAQII/", AAQ2View.as_view(), name="AAQII"),
    path("CAM/", CAM1View.as_view(), name="CAM"),
    path("GAD7/", GAD7View.as_view(), name="GAD7"),
    path("PHQ9/", PHQ9View.as_view(), name="PHQ9"),
    path("RAS/", RASView.as_view(), name="RAS"),
]

sheet4AT/urls.py
from django.contrib import admin
from django.db import router
from django.urls import include, path

from . import views
from .views import AT4View

app_name = "sheet4AT"

urlpatterns = [
    path("sheet4AT/", AT4View.as_view(), name="sheet4AT"),
]

sheetGAD/urls.py
from django.contrib import admin
from django.db import router
from django.urls import include, path

from . import views
from .views import GADView

app_name = "sheetGAD"

urlpatterns = [
    path("GAD/", GADView.as_view(), name="GAD"),
]

sheetPHQ/urls.py
from django.contrib import admin
from django.db import router
from django.urls import include, path

from . import views
from .views import PHQView

app_name = "sheetPHQ"

urlpatterns = [
    path("PHQ/", PHQView.as_view(), name="PHQ"),
]

sheetRAS/urls.py
from django.contrib import admin
from django.db import router
from django.urls import include, path

from . import views
from .views import RASView

app_name = "sheetRAS"

urlpatterns = [
    path("RAS/", RASView.as_view(), name="RAS"),
]

assessment/models.py
from django.db import models

from patient_management.models import Doctor, Patient
import datetime


# Create your models here.
class Stomp(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, null=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    Alternative = models.IntegerField()
    Bluegrass = models.IntegerField()
    Blues = models.IntegerField()
    Classical = models.IntegerField()
    Country = models.IntegerField()
    Dance_Electronica = models.IntegerField()
    Folk = models.IntegerField()
    Funk = models.IntegerField()
    Gospel = models.IntegerField()
    Heavy_Meta = models.IntegerField()
    World = models.IntegerField()


# PsychoemotionalScreeningRecord stuffs
class GAD2(models.Model):
    # 1. Feeling nervous, anxious on edge
    q1_value = models.IntegerField()
    q1_epic = models.CharField('No', max_length=30)
    q1_smf = models.IntegerField()

    q2_value = models.IntegerField()
    q2_epic = models.IntegerField()
    q2_smf = models.IntegerField()

    # Score
    score = models.IntegerField()  # Total Number
    score_epic = models.CharField('No', max_length=30)
    score_smf = models.CharField('FR', max_length=30)

    # Interpretation
    interpretation = models.TextField()
    interpretation_epic = models.CharField('No', max_length=30)
    interpretation_smf = models.CharField('FR', max_length=30)


class GAD7(models.Model):
    q1_value = models.IntegerField()
    q1_epic = models.CharField('No', max_length=30)
    q1_smf = models.IntegerField()

    q2_value = models.IntegerField()
    q2_epic = models.IntegerField()
    q2_smf = models.IntegerField()

    q3_value = models.IntegerField()
    q3_epic = models.CharField('No', max_length=30)
    q3_smf = models.IntegerField()

    q4_value = models.IntegerField()
    q4_epic = models.IntegerField()
    q4_smf = models.IntegerField()

    q5_value = models.IntegerField()
    q5_epic = models.CharField('No', max_length=30)
    q5_smf = models.IntegerField()

    q6_value = models.IntegerField()
    q6_epic = models.IntegerField()
    q6_smf = models.IntegerField()

    q7_value = models.IntegerField()
    q7_epic = models.IntegerField()
    q7_smf = models.IntegerField()

    # Score
    score = models.IntegerField()  # Total Number
    score_epic = models.CharField('No', max_length=30)
    score_smf = models.CharField('FR', max_length=30)

    # Interpretation
    interpretation = models.TextField()
    interpretation_epic = models.CharField('No', max_length=30)
    interpretation_smf = models.CharField('FR', max_length=30)


class PHQ2(models.Model):
    # 1. Feeling nervous, anxious on edge
    q1_value = models.IntegerField()
    q1_epic = models.CharField('No', max_length=30)
    q1_smf = models.CharField('No', max_length=30)

    q2_value = models.IntegerField()
    q2_epic = models.IntegerField()
    q2_smf = models.IntegerField()

    # Score
    score = models.IntegerField()  # Total Number
    score_epic = models.CharField('No', max_length=30)
    score_smf = models.CharField('FR', max_length=30)

    # Interpretation
    interpretation = models.TextField()
    interpretation_epic = models.CharField('No', max_length=30)
    interpretation_smf = models.CharField('FR', max_length=30)


class PHQ9(models.Model):
    q1_value = models.IntegerField()
    q1_epic = models.CharField('No', max_length=30)
    q1_smf = models.IntegerField()

    q2_value = models.IntegerField()
    q2_epic = models.IntegerField()
    q2_smf = models.IntegerField()

    q3_value = models.IntegerField()
    q3_epic = models.CharField('No', max_length=30)
    q3_smf = models.IntegerField()

    q4_value = models.IntegerField()
    q4_epic = models.IntegerField()
    q4_smf = models.IntegerField()

    q5_value = models.IntegerField()
    q5_epic = models.CharField('No''No', max_length=30)
    q5_smf = models.IntegerField()

    q6_value = models.IntegerField()
    q6_epic = models.IntegerField()
    q6_smf = models.IntegerField()

    q7_value = models.IntegerField()
    q7_epic = models.IntegerField()
    q7_smf = models.IntegerField()

    # Score
    score = models.IntegerField()  # Total Number
    score_epic = models.CharField('No', max_length=30)
    score_smf = models.CharField('FR', max_length=30)

    # Interpretation
    interpretation = models.TextField()
    interpretation_epic = models.CharField('No', max_length=30)
    interpretation_smf = models.CharField('FR', max_length=30)


class PsychoemotionalScreeningRecord(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, null=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    GAD2 = models.OneToOneField(GAD2, on_delete=models.CASCADE, )
    GAD7 = models.OneToOneField(GAD7, on_delete=models.CASCADE, )
    PHQ2 = models.OneToOneField(PHQ2, on_delete=models.CASCADE, )
    PHQ9 = models.OneToOneField(PHQ9, on_delete=models.CASCADE, )


class CatCatFlowsheetRecord(models.Model):
    """
    CatCatFlowsheetRecord
    """
    type1_value = models.CharField('eval', max_length=30)
    type1_epic = models.CharField('No', max_length=30)
    type1_smf = models.IntegerField()

    type2_value = models.CharField('treatment', max_length=30)
    type2_epic = models.CharField('No', max_length=30)
    type2_smf = models.IntegerField()

    type3_value = models.CharField('treatment pre', max_length=30)
    type3_epic = models.CharField('No', max_length=30)
    type3_smf = models.IntegerField()

    type4_value = models.CharField('treatment post', max_length=30)
    type4_epic = models.CharField('No', max_length=30)
    type4_smf = models.IntegerField()


class ATModel(models.Model):
    patientName = models.CharField(max_length=255)
    patientNumber = models.CharField(max_length=255)
    birthDate = models.DateField(default=datetime.date.today)
    my_datetime_field = models.DateTimeField()
    TesterName = models.CharField(max_length=255)

    ALERTNESS_CHOICES = [
        ('0', '0 - Normal (fully alert, but not agitated, throughout assessment)'),
        ('0', '0 - Mild sleepiness for <10 seconds after waking, then normal'),
        ('4', '4 - Clearly abnormal'),
    ]
    AMT4_CHOICES = [
        ('0', '0 - No mistakes'),
        ('1', '1- 1 mistake'),
        ('2', '2 or more mistakes/untestable'),
    ]
    ATTENTION_CHOICES = [
        ('0', '0 - Achieves 7 months or more correctly'),
        ('1', '1 - Starts but scores <7 months / refuses to start'),
        ('2', '2 - Untestable (cannot start because unwell, drowsy, inattentive)'),
    ]
    ACUTE_CHANGE_CHOICES = [
        ('0', '0 - No)'),
        ('4', '4 - Yes'),
    ]

    question1 = models.CharField(max_length=1, choices=ALERTNESS_CHOICES, default='0')
    question2 = models.CharField(max_length=1, choices=AMT4_CHOICES, default='0')
    question3 = models.CharField(max_length=1, choices=ATTENTION_CHOICES, default='0')
    question4 = models.CharField(max_length=1, choices=ACUTE_CHANGE_CHOICES, default='0')

    AtScore = models.FloatField()

assessment/forms/StompForm.py
# Copyright 2024 Yuan Chen
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging
from datetime import date

from django import forms


from django.conf import settings
from django.core.mail import EmailMessage, send_mail
from django.forms import ModelForm
from django.http import FileResponse
from django.template.loader import render_to_string
from reportlab.pdfgen import canvas

from assessment.identifiers import Sign
from assessment.models import PsychoemotionalScreeningRecord


class StompForm(forms.Form):
    """
    Music Preference Form
    """

    TherapistEmail = forms.EmailField(label="Therapist Email")
    Alternative = forms.IntegerField(label="Alternative", min_value=1, max_value=5)
    Bluegrass = forms.IntegerField(label="Bluegrass", min_value=1, max_value=5)
    Blues = forms.IntegerField(label="Blues", min_value=1, max_value=5)
    Classical = forms.IntegerField(label="Classical", min_value=1, max_value=5)
    Country = forms.IntegerField(label="Country", min_value=1, max_value=5)
    Dance_Electronica = forms.IntegerField(
        label="Dance/Electronica", min_value=1, max_value=5
    )
    Folk = forms.IntegerField(label="Folk", min_value=1, max_value=5)
    Funk = forms.IntegerField(label="Funk", min_value=1, max_value=5)
    Gospel = forms.IntegerField(label="Gospel", min_value=1, max_value=5)
    Heavy_Meta = forms.IntegerField(label=" Heavy Meta", min_value=1, max_value=5)
    World = forms.IntegerField(label="World", min_value=1, max_value=5)
    Jazz = forms.IntegerField(label="Jazz", min_value=1, max_value=5)
    New_Age = forms.IntegerField(label="New_Age", min_value=1, max_value=5)
    Oldies = forms.IntegerField(label="Oldies", min_value=1, max_value=5)
    Opera = forms.IntegerField(label="Opera", min_value=1, max_value=5)
    Pop = forms.IntegerField(label="Pop", min_value=1, max_value=7)
    Punk = forms.IntegerField(label="Punk", min_value=1, max_value=7)
    Rap_hip_hop = forms.IntegerField(label="Rap/hip-hop", min_value=1, max_value=7)
    Reggae = forms.IntegerField(label="Reggae", min_value=1, max_value=7)
    Religious = forms.IntegerField(label="Religious", min_value=1, max_value=7)
    Rock = forms.IntegerField(label="Rock", min_value=1, max_value=7)
    Soul_R_B = forms.IntegerField(label=" Soul/R&B", min_value=1, max_value=7)
    Soundtracks_heme_song = forms.IntegerField(
        label="Soundtracks/theme song", min_value=1, max_value=7
    )

    def get_info(self):
        form = self
        description = """
                Please indicate your basic preference for each of the following genres using the scale provided.
        1-----------------2-----------------3-----------------4-----------------5-----------------6-----------------7
        Dislike Dislike Dislike a Neither like Like a Like Like
            """
        context = {
            "form": form,
            "header": "STOMP-Revised",
            "description": description,
        }

        result = render_to_string("email/stomp.html", context)
        recipient = form.data["TherapistEmail"]
        return "STOMP-Revised", result, recipient

    def send(self):
        subject, msg, recipent = self.get_info()
        pdf = self.generate_pdf_file().getbuffer()
        email = EmailMessage(
            subject=subject,
            from_email=settings.EMAIL_HOST_USER,
            to=[recipent],
        )
        email.attach("music_preferences.pdf", pdf, "application/pdf")
        email.send()

    def generate_pdf_file(self):
        from io import BytesIO

        buffer = BytesIO()
        p = canvas.Canvas(buffer)

        # Create a PDF document
        p.drawString(100, 750, "Music Preference Form")

        x = 100
        y = 700
        for key in self.data.keys():
            if key != "csrfmiddlewaretoken":
                p.drawString(100, y, f"{key}: {str(self.data[key])}")
                y -= 20

        p.showPage()
        p.save()

        buffer.seek(0)
        return buffer

    def generate_pdf(self):
        response = FileResponse(
            self.generate_pdf_file(),
            as_attachment=True,
            filename="music_preference_form.pdf",
        )
        return response

templates/assessment/CAM.html
{% extends "assessment/base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ header }}{% endblock %}
{% block content %}

    <style>
    /* 字体样式 */
    body {
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        font-size: 16px;
        line-height: 1.6;
    }

    /* 表格样式 */
    .table-striped th,
    .table-striped td {
        padding: 12px; /* 增加填充以创建更多空间 */
        text-align: left; /* 左对齐表头和单元格内容 */
    }

    .table-striped th {
        background-color: #00b7a6; /* 指定的颜色 */
        color: #ffffff; /* 白色文本 */
    }

    .table-striped tbody tr:nth-child(odd) td {
        background-color: #00b7a6; /* 指定的颜色 */
        color: #ffffff; /* 白色文本 */
    }

    .table-striped tbody tr:nth-child(even) td {
        background-color: #ffffff; /* 白色背景 */
        color: #00b7a6; /* 深色文本 */
    }

    /* 按钮样式 */
    .btn-success {
        padding: 10px 20px; /* 增加按钮的填充 */
        font-size: 18px; /* 增大字体大小 */
        border-radius: 5px; /* 圆角按钮 */
    }

    .label-color {
        color: #00b7a6; /* 这里是你选择的颜色 */
        font-weight: bold; /* 字体加粗 */
        font-size: 16px; /* 字体大小，根据需要调整 */
    }

</style>


<script>
        function performDivision() {

          document.getElementById('id_checkbox5').checked = false;
           document.getElementById('id_checkbox6').checked = false;

            // Get the values from the numerator and denominator input fields
            var oneValue = document.getElementById('id_checkbox1');
            var twosValue = document.getElementById('id_checkbox2');
             var threeValue = document.getElementById('id_checkbox3');
              var fourValue = document.getElementById('id_checkbox4');

            // Convert the values to numbers
            var check1 = oneValue.checked;
            var check2 = twosValue.checked;
            var check3 = threeValue.checked;
            var check4 = fourValue.checked;
            var index = false

           if (check1 && check2 && (check3 || check4)) {
                  index = true
            }


            if(index){
             document.getElementById('id_checkbox5').checked = true;
            }else{
            document.getElementById('id_checkbox6').checked = true;
            }
            // Perform the division and update the result input field



        }
    </script>
    <div class="container-fluid text-center">
        {{ description |escape|linebreaks }}
    </div>
    <form class="container" action="" method="post">
        {% csrf_token %}
        <label for="id_patientName" class="requiredField label-color">
            Patient<span class="asteriskField">*</span>
        </label>
        <div>
             {{ form.patientName }}
        </div>
         <label for="id_my_datetime_field" class="requiredField label-color">
          Time  <span class="asteriskField">*</span>
        </label>
        <div>
             {{ form.my_datetime_field }}
        </div>
        <table class="table table-striped">

            <tr>
                <th>

                </th>
                <th>

                </th>
                <th>

                </th>

            </tr>
            {#            {% for field in form %}#}
            <tr>
                <td>
                    <div>
                         1. Acute Onset or Fluctuating Course
                    </div>
                    <div>
                         Is the pt different than his/her baseline mental status? OR
Has the patient had any fluctuation in mental status in the past 24 hours as evidenced by fluctuation on a sedation scale (i.e., RASS), GCS, or previous delirium assessment?

                    </div>
                </td>

                <td>
                        Either question Yes ->
                </td>
                 <td>
                    {{ form.checkbox1 |as_crispy_field }}
                    {#                    placeholder#}
                </td>

            </tr>

            <tr>
                <td class="fieldWrapper">
                    {{ form.feature1.errors }}
                    {{ form.feature1.label_tag }}
                        <div>
                            2. Inattention
                        </div>
                    <div>
                          Directions: Say to the patient, "I am going to read you a series of 10 letters. Whenever you hear the letter 'A,' indicate by squeezing my hand.” Read letters from the following letter list in a normal tone 3 seconds apart.
SAVEAHAART
Errors are counted when patient fails to squeeze on the letter "A" and when the patient squeezes on any letter other than “A.”
                    </div>

                </td>

                <td>
                    Number of Errors >2 →→
                </td>

                  <td>
                    {{ form.checkbox2 |as_crispy_field }}
                    {#                    placeholder#}
                </td>

            </tr>
            <tr>
                <td class="fieldWrapper">
                    {{ form.feature1.errors }}
                    {{ form.feature1.label_tag }}
                    <div>
                        3. Altered Level of Consciousness
                    </div>
                    <div>
                        Present if the Actual RASS score is anything other than alert and calm (zero)
                    </div>
                </td>
                <td>
                        RASS anything other than zero ->
                </td>

                  <td>
                    {{ form.checkbox3 |as_crispy_field }}
                    {#                    placeholder#}
                </td>

            </tr>

             <tr>
                <td class="fieldWrapper">
                    {{ form.feature1.errors }}
                    {{ form.feature1.label_tag }}
                     <div>
                        4. Disorganized Thinking
                    </div>
                    <div>
                         Yes/No Questions (See training manual for alternate set of questions)
                    1. Will a stone float on water?
                    2. Are there fish in the sea?
                    3. Does one pound weigh more than two pounds?
                    4. Can you use a hammer to pound a nail?
                    Errors are counted when the patient incorrectly answers a question.
                    Command
                    Say to patient: "Hold up this many fingers" (Hold 2 fingers in front of patient) "Now do the same thing with the other hand" (Do not repeat number of fingers) *If pt is unable to move both arms, for 2nd part of command ask patient to "Add one more finger"
                    An error is counted if patient is unable to complete the entire command.
                    </div>



                </td>
                <td>
                     Combined number of errors > 1->

                </td>


                  <td>
                    {{ form.checkbox4 |as_crispy_field }}
                    {#                    placeholder#}
                </td>

            </tr>
              <tr>
                <td class="fieldWrapper">
                    {{ form.feature1.errors }}
                    {{ form.feature1.label_tag }}
                    <div>
                         Feature 1 plus 2 and either 3 or 4 present = CAM-ICU positive
                    </div>


                </td>
                <td>
                    <div>
                        Criteria Met ->
                    </div>
                    <div>
                        Criteria Not Met ->
                    </div>

                </td>
                <td>
                       <div>
                           {{ form.checkbox5 |as_crispy_field }}
                       </div>
                    <div>
                          {{ form.checkbox6 |as_crispy_field }}
                    </div>


                </td>

            </tr>

            {#            {% endfor %}#}
        </table>
        <button class="btn my-3" type="submit" style="background-color: #00b7a6; color: #ffffff;">Send message</button>
    
    </form>

{% endblock %}

templates/assessment/Psychoemotional_Screening_Evaluation.html
{% extends "assessment/base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ header }}{% endblock %}
{% block content %}
    <div class="container text-center">
        {{ description |escape|linebreaks }}
    </div>
    {#    {% include 'assessment/form_snippet.html' %}#}
    <div class="container">
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field|as_crispy_field }}
            </div>
        {% endfor %}
        {#    {% include 'assessment/form_snippet.html' %}#}
        <button class="btn btn-success my-3" type="submit">Send message</button>
        <button class="btn btn-primary my-3" type="submit">Download PDF</button>
    </div>

{% endblock %}

templates/assessment/footer.html
<div class="footer">
    <div class="container-fluid text-center">
        <!-- <hr> -->
        <span class="text-muted"> Created with ❤️ by Yuan Chen.</span>

        <a href="/admin"> Admin</a> · <a
            href="/admin/admin/logentry/">Logs</a> · <a href="/about">About</a>

        </span>
    </div>
</div>

templates/assessment/form_snippet.html
<div class="row">
    <div class="col-6 col-lg-2 mb-3">
        <label>Therapist</label><input class="form-control" type="text" value="{{ therapist }}" readonly>
    </div>
    <div class="col-6 col-lg-2 mb-3">
        <label>Patient</label><input class="form-control" type="text" value="{{ patient }}">
    </div>
    <div class="col-6 col-lg-2 mb-3">
        <label>Date</label><input class="form-control" type="datetime-local">
    </div>

    <div>
        <button class="btn btn-light">Save</button>
        <button class="btn btn-light">Edit</button>
        <button class="btn btn-light">Delete</button>
    </div>
</div>

templates/assessment/index.html
{% extends "assessment/base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ header }}{% endblock %}
{% block content %}
    <div class="form-group">
        <label for="patientName">Patient Name:</label>
        <input type="text" class="form-control" id="patientName" placeholder="Enter patient's name">
    </div>
    <label> Assessment Form Name:
        <select class="form-control">
            <option class="dropdown-item" href="{% url "assessment:Neurologic_Screening_Evaluation" %}">Neurologic
                Screening Evaluation
            </option>
            <option class="dropdown-item" href="{% url "assessment:pre_post_tests" %}">Pre Post Tests</option>
            <option class="dropdown-item" href="{% url "assessment:Psychoemotional_Screening_Evaluation" %}">
                Psychoemotional
                Screening Evaluation
            </option>
            <option class="dropdown-item" href="{% url "assessment:stomp" %}">Music Preference</option>
            <option class="dropdown-item" href="{% url "sheetRAS:RAS" %}">RAS Evaluation</option>
            <option class="dropdown-item" href="{% url "sheet4AT:sheet4AT" %}">4AT Evaluation</option>
            <option class="dropdown-item" href="{% url "sheetCAM1:CAM1" %}">4AT Evaluation</option>
            <option class="dropdown-item" href="{% url "sheetAAQII:AAQII" %}">AAQII Evaluation</option>
            <option class="dropdown-item" href="{% url "sheetGAD:GAD" %}">GAD-7 Evaluation</option>
            <option class="dropdown-item" href="{% url "sheetPHQ:PHQ" %}">PHQ9 Evaluation</option>
            </div>
        </select>
    </label>
    <button class="btn btn-primary my-3" type="submit">Create</button>
{% endblock %}

templates/assessment/pre_post_form.html
{% extends "assessment/base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ header }}{% endblock %}
{% block content %}
    <div class="container text-center">
        {{ description |escape|linebreaks }}
    </div>
    <form class="container" action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field|as_crispy_field }}
            </div>
        {% endfor %}
        <button class="btn btn-success my-3" type="submit">Send message</button>
        <button class="btn btn-primary my-3" type="submit">Download PDF</button>
    </form>
{% endblock %}